.github/workflows/test_and_lint.yaml, .github/workflows/test_and_static_analysis.yaml
ref #5 
- github actionsでテストを実行
- 静的解析を実行
=> GithubActionsでテストとLintする

main.go
- シグナルを見落とさないようにバッファーをつける
- ref : https://golang.org/pkg/os/signal/#Notify
=> シグナルを見落とさないようにバッファーをつける

database/auth.go, database/auth_test.go, domain/entity/errors.go, domain/mock_spotify/auth.go, domain/spotify/auth.go, go.mod, spotify/client.go, usecase/auth.go, web/auth_middleware.go, web/auth_middleware_test.go, web/router.go
close #12 
- ミドルウェアでアクセストークンの有効期限チェックと更新処理を挟むようにしました
=> [Auth] 有効期限が切れたアクセストークンの更新処理を行う

domain/entity/user.go, domain/entity/user_test.go, usecase/user.go, web/handler/user.go, web/handler/user_test.go
close #21 
- プレミアム会員かどうかの情報をSpotify APIから取得する
=> [User] GET /users/me でプレミアムかどうかを取得できていなかったので処理を追加

config/config.go, config/config_test.go, env.local, env.test, main.go
=> ポート番号を環境変数から読み込む

docs/api.md, domain/entity/session.go, domain/entity/session_test.go, main.go, usecase/session.go, web/handler/auth.go, web/handler/session.go, web/handler/session_test.go, web/handler/track.go, web/handler/track_test.go
#49 
- POST /sessions を実装
https://github.com/camphor-/relaym-server/blob/master/docs/api.md#post-sessions
=> Session作成のAPIを作成（Post /sessions）

web/router.go
- PostSessionをrouterに登録し忘れていたので追加
=> PostSessionをrouterに登録し忘れていたので追加

spotify/player.go, web/router.go
- AddQueueのrouterを追加
- URIの切り取り処理が間違っていたので修正
=> キューへの追加処理の細かい部分を修正

domain/entity/session.go, testdata/e2e.js, usecase/session.go
=> 全曲が再生された後に曲が追加された際の挙動を修正

README.md, database/auth.go, database/auth_test.go, domain/entity/errors.go, mysql/schemas/relaym/login_session.sql
#74 
- ログインセッションをオンメモリ→MySQLで保持
- login_sessionsテーブルを作成
=> ログインセッションをMySQLに移行

docs/development.md
- 環境構築時のskeemaのマイグレートについて、パスワード？となってので説明を補足しました
=> skeemaのマイグレート時の説明を補足

domain/entity/track.go, spotify/player.go, testdata/e2e.js, usecase/session.go, web/handler/session_test.go
close #75 
- デバイスIDを指定してSpotifyAPIを叩く
-
=> デバイスIDを指定してSpotifyAPIを叩く

docs/api.md
=> POST /sessionsのレスポンスの型が違ったので修正

config/config_test.go, env.local, env.test
=> CORSの設定が間違っていたので修正

web/router.go
=> Allow credentials trueを追加

web/router.go
=> X-CSRF-Tokenをヘッダーに追加

web/router.go
- CSRFトークンが正しいかを返すべきところを逆の条件で記述していた
=> CSRFトークンの判定条件が仕様と逆だったのを修正

domain/entity/track.go
=> Trackがnilのときは0を返す

docs/api.md, web/handler/session.go
=> STOPのときにPAUSEにしようとすると400エラーを返すようにする

testdata/e2e.js
=> e2eテスト時に正しいcsrfトークンを使う

web/deploy_preview_cors_middleware.go, web/deploy_preview_cors_middleware_test.go, web/router.go
なし
- Dev環境のときだけNetlifyのDeploy PreviewからAPIを叩けるようにした
@dora1998 欲しそうだったので実装しました！！
=> Dev環境のときだけNetlifyのDeploy PreviewからAPIを叩けるようにする

web/deploy_preview_cors_middleware.go, web/deploy_preview_cors_middleware_test.go, web/router.go
- `OPTIONの`ときはのaddAllowOriginForOptionで204を返す
- そのほかのときはechoの `CORSWithConfig ` と通した後 `addAllowOrigin` に行く
=> OPTIONのときだけ独自のmiddlewareで204を返す

web/handler/websocket.go
これを消した
https://github.com/camphor-/relaym-server/pull/117/files
=> バグ見つけるために一時的に設定したLogの削除

.github/workflows/test_and_lint.yaml, web/ws/conn.go, web/ws/hub_test.go
- golangci-lintの設定で色々なものをチェックするようにした
=> 多くの静的解析ツールをCIで実行するようにする

docs/api.md, docs/prd.md, docs/sotify_api_problem.md, domain/entity/errors.go, domain/entity/event.go, domain/entity/session.go, domain/entity/session_test.go, mysql/schemas/relaym/sessions.sql, testdata/e2e.js, usecase/session.go, web/handler/session.go, web/handler/session_test.go, web/router.go
#122 
- /playbackを/stateにrename
- 手動アーカイブ・アーカイブ解除を/stateで行う
- sessions.stateにARCHIVEDを追加
先に手動アーカイブの方のみ実装しました
=> 手動アーカイブを実装

web/handler/session_state_test.go
=> 切り出したテスト用のヘルパー関数を使ってなかったので修正

.github/workflows/deploy-prod.yaml, mysql/schemas/.skeema
#140 
- skeemaの設定ファイルにprodを追加
-
=> skeemaの設定ファイルにprodを追加

docker/docker-entrypoint.sh
#140 
何回もデプロイし直してたら大変なことになったので
```
bash-5.0# cat .skeema
default-character-set=utf8mb4
default-collation=utf8mb4_bin
schema=relaym_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod_prod
bash-5.0#
```
=> sedで行頭行末を指定する

docs/database.md
close #140 
- 権限の設定を分かりやすくdocsに書く
=> GRANTの例を追加

domain/service/auth.go, web/sessionToken_middleware.go
=> CreatorTokenMiddlewareの場合もログイン済みならuserIDをコンテキストにセットする

usecase/session.go, usecase/session_timer.go
=> 不必要なStopTimerを削除

web/handler/session.go
=> プログレスバーがNanになっていた問題を修正

usecase/session.go, usecase/session_timer.go, web/ws/conn.go
なし
- 要らないログを消す
- err.Error()にしてstringでエラーを吐く
=> [Refactor] エラーログを調整

.github/workflows/test_and_lint.yaml, Makefile, README.md
=> カバレッジを計測する

spotify/player_test.go, spotify/track.go, spotify/track_test.go
#155 
- GetTracksFromURIで50曲以上の場合も正常にTracksが取得できるようにした
-
=> GetTracksFromURIで50曲以上の場合も正常にTracksが取得できるようにした

database/session.go, database/session_test.go, domain/mock_repository/session.go, domain/repository/session.go, usecase/session_timer.go, usecase/session_timer_test.go
#152 
- handleTrackendをトランザクションで実行することで、GetSessionが叩かれたとしてもロック待ちになるようにする
=> handleTrackendでトランザクションを使う

README.md
=> GitHub Actionsのバッジを追加

docs/prd.md, usecase/session_state.go
- Archive周りのstateの変更に関する記述をprdとfuncのコメントに追加
- creatorであるかのチェックをarchiveToStopで呼び出すように変更
=> Archive周りのstateの変更に関する記述の追加&一部処理の移動

database/session.go, database/session_test.go, domain/entity/session.go, domain/entity/session_test.go, domain/mock_spotify/player.go, domain/spotify/player.go, mysql/schemas/relaym/sessions.sql, spotify/player.go, usecase/session_state.go, usecase/session_test.go, web/handler/session_state_test.go
close #168 
- PAUSEするときに現在の再生時間を保存して、PAUSE→PLAY時にその再生位置から再生し始めることで、想定される曲の再生を始めることで、INTERRUPTにならないようにする
=> PAUSEするときに現在の再生時間を保存して、PAUSE→PLAY時にその再生位置から再生し始める

web/ws/conn.go
=> 無視していいエラーではWARNログを出さない

go.mod, go.sum, spotify/track.go
close #176 
- パッチのPRを出しているが、まだマージされないので、一旦p1assのリポジトリを参照するように変更
- https://github.com/zmb3/spotify/pull/131
- https://github.com/p1ass/spotify
- Aceept-Languageをセットする
=> AcceptLanguageを設定して、日本語で曲情報を取得するようにする

domain/mock_spotify/player.go, domain/spotify/player.go, usecase/session_state.go, web/handler/session_state_test.go
=> 曲再生時に明示的に秒数を指定する

.github/workflows/test_and_lint.yaml, README.md, docker/Dockerfile, go.mod
=> bump go version to 1.15

.github/workflows/deploy-dev.yaml, Makefile, docker/docker-compose.base.yml
=> Dev環境、GitHub Actionでbuild と deploy

.github/workflows/deploy-prod.yaml, Makefile
=> Prod環境、GitHub Actionでbuild と deploy

docker/docker-compose.dev.yml, docker/docker-compose.prod.yml
=> caddyへの移行に伴いport bindingを消す

docs/development.md
- m1 macを使用する開発者向けにドキュメントの追加
- 
https://twitter.com/kissessenose/status/1393820736221970435
=> m1 macを使用する開発者向けにドキュメントの追加

web/deploy_preview_cors_middleware.go, web/deploy_preview_cors_middleware_test.go
なし
- relaym-client側のデプロイをCloudflare Pagesに変えたいという話があるので、Cloudflare PagesのCORSに対応する
=> Cloudflare Pagesのプレビュー環境に対応する

web/deploy_preview_cors_middleware.go
=> Deploy Preview時にAccess-Control-Allow-Credentialsがついてなかったので修正

.github/workflows/deploy-dev.yaml
=> update image tag to deploy konoe cluster via argocd

.github/workflows/deploy-dev.yaml
=> Fix incorrect action dispatch
