database/auth.go
database/auth_test.go
domain/repository/auth.go
mysql/schemas/relaym/spotify_auth.sql
usecase/auth.go
web/handler/auth_test.go
web/handler/user_test.go

#11 
- Spotifyのアクセストークンを保存する処理を追加
- APIコール時にアクセストークンを取得する処理は別PRにします
- spotifyUserIDを取得する処理も別PRにします

[Auth] Spotifyのアクセストークンを保存する処理を追加

---

database/session.go
database/session_test.go
domain/entity/session.go
domain/entity/session_test.go
usecase/session.go
web/handler/session_test.go

close #18 
- 曲の一時停止用のAPIを実装
-  冪等性担保のために Play→Play、 Pause→Pauseの状態遷移はエラーにしない
- フィールドの値が全てDBの値を一致するセッションで更新した際にエラーになるバグがあったので修正

曲の一時停止用のAPIを実装

---

database/session.go
spotify/player.go
spotify/player_test.go
usecase/session.go
web/handler/session.go
web/handler/session_test.go

#19 
- POST /sessions/:id/queue を実装
https://github.com/camphor-/relaym-server/blob/master/docs/api.md#post-sessionsidqueue
spotify.AddToQueueの引数が元々trackIDを取るようになっていたのですが、アプリケーション内でtrackURIを使うことが多いと感じたのでspotify.AddToQueueの引数ではtrackURIを受け取り、内部でtrackIDに変換する形にしました。spotify.AddToQueueはそのままに、usecase内でtrackURIをtrackIDに変換するのと迷ったのですが、どちらがいい（もしくは他にこうしたほうが良い）とかありますか？

Queueに曲を追加するAPIを生やす

---

main.go

なし
- サーバの起動が失敗したときにプロセスが終了していなかったので、終了するように変更

サーバの起動失敗時に終了コード1で終了する

---

domain/entity/event.go
usecase/session.go
web/handler/session_test.go

#31 
- 曲の追加時にADDTRACKイベントを送信
- 曲の一時停止時にPAUSEイベントを送信

[WebSocket] ADDTRACKイベントとPAUSEイベントの送信処理を実装

---

docs/api.md
domain/entity/track.go
domain/mock_spotify/track.go
domain/spotify/track.go
main.go
spotify/player.go
spotify/track.go
usecase/session.go
usecase/session_test.go
web/handler/session.go
web/handler/session_test.go
web/handler/track.go
web/router.go

#48 (#59 )
- GET /sessions/:idを実装
https://github.com/camphor-/relaym-server/blob/master/docs/api.md#get-sessionsid
勝手に400（"empty session id"）も追加しちゃったんですけど、idがない状態で渡ってきたときも404の方がよかったですか？？

sessionの情報を取得するGET /sessions/:idを実装

---

database/session.go
domain/entity/session.go
domain/mock_spotify/player.go
domain/spotify/player.go
spotify/player.go
testdata/e2e.js
usecase/session.go
web/handler/session_test.go
web/router.go

close #20 
close #66 
- 今までは /queue APIが呼ばれるたびにSpotifyのAPIを呼んでいたが、これからは再生開始した後だけ毎回呼ばれるようにし、再生される前のものは再生開始時にバルクでキューに積むようにする
- これのおかげで、全く違う曲を再生していたときに /playback で再生を始めるとキューの1曲目が再生されるようになる
- ついでに次の曲への自動で遷移する
- 間違ってたSQLを修正

 Stop→Play時に全てのキューをSpotifyに投げて再生を始めることで、今の曲を強制的に中断させて再生を開始させる

---

domain/entity/event.go
usecase/session.go
usecase/session_test.go

close #31 
- NextTrackイベント時にheadの値を送信するようにする

NextTrackイベント時にheadの値を送信するようにする

---

database/session.go
database/session_test.go
docs/api.md
domain/mock_repository/session.go
domain/repository/session.go
domain/service/auth.go
main.go
usecase/auth.go
web/auth_middleware_test.go
web/handler/auth_test.go
web/router.go
web/sessionToken_middleware.go
web/sessionToken_middleware_test.go

#46 
- Spotifyにログインしていなくても検索を行える&プレイヤーを操作できる
- 有効期限が切れていた場合はAuthMiddlewareと同様にRefreshする
結局sessionのTableにtokenを持たせずにJOINで頑張りました(リフレッシュトークンとか色々も持たせるとなるとめんどくさかった…）

sessionのCreatorのTokenをみんなで使おうZE！

---

spotify/track.go
web/handler/session.go
web/router.go

#82 
- 空の配列がGetTracksFromURIのtrackURIsに渡されるとspotifyAPIがerrを返してしまう（`invalid id`を返すのでnilであることを受け取れない）のでその手前でtrackURIsが空であるかをチェック
- toTrackにnilが渡されるとダメなのでチェック（Trackが空のときにGetSessionを叩くとCurrentlyPlayingでtoTrackをnilで呼び出してしまう）
- GetSessionのrouteが間違ってるので修正
ワイが犯人です（どげざ

GetSession周りのバグの修正

---

web/sessionToken_middleware.go

#84 
ref: https://github.com/camphor-/relaym-server/blob/master/docs/api.md#get-sessionsid
- sessionTokenMiddlewareでの処理が一部おかしかった

GetSessionでsessionIDからsessionが見つからない時には404を返したいんだ

---

domain/entity/session.go
domain/entity/session_test.go
usecase/session.go

- Stopならnilを返すように修正
- Stop以外でplayingInfoがnilならエラーにする
```
2020-06-28T05:31:42.930354361Z {"time":"2020-06-28T05:31:42.93002584Z","level":"-","prefix":"echo","file":"recover.go","line":"73","message":"[PANIC RECOVER] runtime error: index out of range [0] with length 0 goroutine 187 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1(0x9cbf10, 0x1000, 0x0, 0xa77780, 0xc000438140)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/recover.go:71 +0xee\npanic(0x9700e0, 0xc000399400)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\ngithub.com/camphor-/relaym-server/domain/entity.(*Session).IsPlayingCorrectTrack(0xc000370150, 0xc0000bbdc0, 0xc000193530, 0xc0000bbdc0)\n\t/go/src/github.com/camphor-/relaym-server/domain/entity/session.go:103 …
```

キューがからのときにセッションの同期チェックメソッドがpanicになっていた問題を修正

---

web/handler/websocket.go

- websocket接続時にHTTPリクエストのログを表示する
```
GET /api/v3/sessions/57ea18a2-966e-492b-b24c-411ed75599de/ws HTTP/1.1
Host: relaym.local:8080
Accept-Encoding: gzip, deflate
Accept-Language: ja,en;q=0.9
Cache-Control: no-cache
Connection: Upgrade
Origin: http://relaym.local:3000
Pragma: no-cache
Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
Sec-Websocket-Key: 8HDwAb68bAquOji+WiIw4g==
Sec-Websocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
```

websocket接続時にHTTPリクエストのログを表示する

---

docker/docker-compose.base.yml

https://github.com/docker/compose/issues/2231
- なんと `tty: true`  をつけるだけでdocker logs でも色がつくのです

docker logs で色がつくようにtty:trueをセットする

---

domain/entity/session.go
domain/entity/session_test.go
domain/mock_spotify/player.go
domain/spotify/player.go
spotify/player.go
spotify/player_test.go
usecase/session.go
usecase/session_test.go
web/handler/session_test.go

#125 #86 
- skipのAPIを使用して「次に再生される曲」を飛ばす
- playWithTracksで「再生待ち」をリセットできることを利用してダミーの曲をplayWithTracksして「再生待ち」を0曲にする
- 「次に再生される曲」が溜まっているとskipに時間がかかるためRelaymが「次に再生される曲」にためる曲数を常に最大2曲にする（セッション開始前にユーザーが「次に再生される曲」に溜めてた場合はあんまり考えていない）
通話してた時の僕「ん〜まあ1, 2時間で終わります!w」
今の僕「4時間ちょいかかったが…？」

「次に再生される曲」周りの色々な問題を†完全に解決†した

---

spotify/track.go

for rangeで回しているスライスのvalueのポインタを他の関数に渡すのはまずい。
やらかすとこういうバグを踏み抜くことになる。
https://blog.p1ass.com/posts/pointer-of-for-range-loop-of-go/
gosecはこういう危険なコードを検出してくれる静的解析ツール。
(GoLandならFile Watcherでgofmtと同じように設定できるのでオススメ)
```
/usr/local/bin/golangci-lint run --disable=typecheck --enable=gosec,prealloc,gocognit /Users/plus/ghq/github.com/camphor-/relaym-server/spotify
spotify/track.go:63:25: G601: Implicit memory aliasing in for loop. (gosec)
tracks[i] = c.toTrack(&rt)
```
- ループ内で再度変数を生成してバグる危険性をなくす

gosecのエラーをなくす

---

domain/service/auth.go
domain/service/auth_test.go
usecase/session.go
web/handler/session_test.go
web/sessionToken_middleware.go
web/sessionToken_middleware_test.go

#128 
- ログインユーザの情報は Contextの userID に、セッション作成者のIDは creatorIDにセットする
-  セッション作成者からのリクエストのときのみ、PAUSE→PLAYでactive device not foundになっても再生処理を続行する
-

 セッション作成者からのリクエストのときのみ、PAUSE→PLAYでactive device not foundになっても再生処理を続行する

---

usecase/session_state.go
web/handler/session_state_test.go

#128
- クライアント側でダイアログを出すことになったので消す
https://github.com/camphor-/relaym-client/issues/195#issuecomment-662820351

「再生するデバイスがオフラインかつセッション作成者のリクエストのときは403を返しつつも再生処理を行う」仕様を消す

---

main.go
usecase/session.go
usecase/session_test.go
usecase/session_timer.go
usecase/session_timer_test.go
web/handler/session_state_test.go
web/handler/session_test.go

#119 
- timerをhandletrackEndの頭で削除
- timerが存在しない時はsyncCheckOffsetの時間なのでcpiのチェックは飛ばすように変更
テスト通ってえええええ

[WIP] タイミングが悪いとget sessionsでInterruptする

---

usecase/session_timer.go
usecase/session_timer_test.go

close #152 
- 曲の再生が終わる前にタイマーを発火するようにして、Spotify側が次の曲に行く前にDeleteTimerが呼ばれるようにする。
- タイマーが消されることで、GetSession呼び出し時にINTERRUPTにならなくなる

曲の切替時にINTERRUPTが送られてくる問題を修正

---

database/session.go
database/session_test.go
database/transaction.go
domain/mock_repository/session.go
domain/repository/session.go
go.sum
usecase/auth.go
usecase/session.go
usecase/session_state.go
usecase/session_test.go
usecase/session_timer.go
usecase/session_timer_test.go
web/handler/session.go
web/handler/session_state_test.go
web/handler/session_test.go
web/sessionToken_middleware_test.go

- ctxにトランザクションの構造体が詰められているかどうかでトランザクションを使うか切り替えます。
- `DoInTx()` の `f` に渡された関数の中でRepositoryの関数を呼べば、勝手にトランザクションで処理を実行してくれます 
参考: https://qiita.com/miya-masa/items/316256924a1f0d7374bb

repositoryでトランザクションを使えるようにする

---

usecase/session_state.go
web/handler/session_state_test.go

#122 
- ARCHIVEとSTOPのときはセッション作成者しか操作できないようにする

ARCHIVEとSTOPのときはセッション作成者しか操作できないようにする

---

usecase/session.go
web/handler/session_test.go

- GetSessionでのセッション取得時にFOR UPDATEをつけることで、曲の切り替え時にGetSessionしようとしてもINTERRUPTにならないようにする

GetSessionでのセッション取得時にFOR UPDATEをつける

---

docs/api.md
domain/entity/session.go
domain/entity/session_test.go
domain/entity/sync_check_timer.go
domain/entity/sync_check_timer_test.go
domain/mock_spotify/player.go
domain/spotify/player.go
spotify/player.go
spotify/player_test.go
usecase/session.go
usecase/session_state.go
usecase/session_test.go
usecase/session_timer.go
usecase/session_timer_test.go
web/handler/session.go
web/handler/session_state_test.go
web/handler/session_test.go
web/router.go

Reverts camphor-/relaym-server#179

Revert "Revert "曲のSkipのためのAPIを実装した""

---

go.mod
go.sum
spotify/client.go
spotify/track.go

なし
- レスポンスを速めるために、キャッシュできるAPIをキャッシュする

track APIのレスポンスをオンメモリでキャッシュする

---

domain/entity/session.go
domain/entity/session_test.go
usecase/session_timer.go

もしかしたら #184 
- Spotifyが一時停止中だと、曲情報は入っているが Playingはfalseという状況になる。このとき、SessionのStateがPlayなら意図しない挙動なのでINTERRUPTになるようにする

同期チェックでPlayingが正しいかもかもチェックする

---

database/session.go
database/session_test.go

close #183 
- `AllowToControleByOthers` がtrueのもののみアーカイブするようにした

他人への操作が許可されていないときはセッションをアーカイブしない

---

usecase/session_timer.go
usecase/session_timer_test.go

close #185
- 再生終了時に新規に曲をSpotifyのキューに追加する処理はhandleWaitTimerExpiredの方で行うことで、active device not foundのときに正しくINTERRUPT処理が行われるようにする

handleTrackendTxでactive device not foundになったときにERRORになっていた問題を修正

---

domain/entity/session.go
domain/entity/sync_check_timer.go
usecase/session_state.go
usecase/session_state_test.go
usecase/session_timer.go
usecase/session_timer_test.go
web/handler/session_test.go

#192 #190
#193 のコメントで書いた
> これDBのトランザクションを使えばもっとスマートに解決できる気がしてきた
https://github.com/camphor-/relaym-server/pull/193#issuecomment-671187287
を上手く説明できる気がしなかったのでPR作ってみました
- StateがPAUSE、STOPのときは処理をDBのトランザクションで囲むことで、APIコールごとに直列で処理を行うことで、タイミングによって、動作がおかしくなるといったことはなくなる。
- `sendToNextTrackNotToExceedCap()` でチャネルのキャパシティ以上呼び出されても、チャネルにメッセージを送らず破棄するようにする。これでPLAY時にAPIを超絶大量に投げられても、デッドロックすることはなくなり、スキップをちゃんとされる。
- そもそも連打を全て律儀にスキップする必要はない（それは考えうる動作でないので）という発想からの実装
- `DoInTx` で囲むとハンドラーレイヤーからテストを書きづらいので、正常系のテスト(DoInTxの中を確かめる必要があるテスト）はユースケース側に持ってきた

大量にskipAPIが叩かれても同時に処理しないようにした (トランザクションとレートリミットを使ってみたパターン)

---

.github/workflows/test_and_lint.yaml
docker/Dockerfile
go.mod
go.sum

上げようと思った要因
`test_and_lint.yaml`の`Get tools`で以下のようなエラーが出て、CIの結果が根こそぎ赤になっている。
(`os.ReadDir`も`os.ReadFile`もadded in go1.16なのが原因)
```
Run GO111MODULE=off go get -u github.com/skeema/skeema
Error: ../../../go/src/github.com/skeema/skeema/vendor/github.com/containerd/containerd/sys/fds.go:30:15: undefined: os.ReadDir
Error: ../../../go/src/github.com/skeema/skeema/vendor/github.com/containerd/containerd/sys/oom_linux.go:[7](https://github.com/camphor-/relaym-server/runs/6196083637?check_suite_focus=true#step:7:8)1:15: undefined: os.ReadFile
Error: Process completed with exit code 2.
```

Upgrade Golang Version 1.15 → 1.18
